"""add corrections, persistent_file, diff_log_tables

Revision ID: 8bb7caa98890
Revises: ff7eaaa0d601
Create Date: 2026-09-29 12:01:50.525690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb7caa98890'
down_revision: Union[str, Sequence[str], None] = 'ff7eaaa0d601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
